### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by XJtsinghua1992** [KazMorita/polyhedron_distortion#2]
Hi Kazuki Morita,
I used your newly developed polyhedron_distortion/polyhedron_analysis.py and found that some structures work well. However, some structures still show the same warning after adjusting the CrystallNN parameter. Can you help to check this?

I attach the POSCAR here. "python polyhedron_analysis.py POSCAR-wrong 84"
[POSCAR-wrong.txt](https://github.com/KazMorita/polyhedron_distortion/files/13371379/POSCAR-wrong.txt)

**Comment by XJtsinghua1992** [comment]
Hi Kazuki Morita,

Could you kindly help check it?
Thank you very much

**Comment by KazMorita** [comment]
Hi,

I'll take a look into this later in the week. I'll probably write a new script.

**Comment by KazMorita** [comment]
I've taken a look and made a new script.

```
$ python polyhedron_analysis_set_ligands.py POSCAR-wrong.txt 84 189 210 228 243 280 263                                                                                                 #Eg, T2g, T1u, T2u, T1u(centre)
[0.08967445 0.33298157 0.18260825 0.21523937 0.17111988]
```
You should get something like this.

The distortion around atom 84 is VERY large. My method is designed to analyse octahedron environment and cannot ensure validity if the structure is too far away from octahedron. Please be careful and double check if the final values make a physical sense.

**Comment by XJtsinghua1992** [comment]
Hi Kazuki Morita,
 Thank you very much for your help.

**Comment by XJtsinghua1992** [comment]
Hi Kazuki Morita,

I've noticed that some structures have large output parameters, but their octahedral distortion doesn't look large at first glance. Can you help to check this? Thank you very much.

python polyhedron_analysis.py POSCAR/POSCAR-580 1
[POSCAR-580.txt](https://github.com/KazMorita/polyhedron_distortion/files/13941417/POSCAR-580.txt)

**Comment by KazMorita** [comment]
Hi,

Could you interpolate the structure between the ideal octahedra and see how the values change?
It might be that the theory is not suitable for too large distortions.
